import 'dart:async';

import 'package:firebase_messaging/firebase_messaging.dart';

import '../firebase/firebase_initializer.dart';
import '../logging/app_logger.dart';
import 'notification_service.dart';

/// Background isolate handler. Must be a top-level function.
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Keep this lightweight: heavy work belongs server-side. The transaction →
  // partner push is generated by a Supabase Edge Function (see docs), so here
  // we only need Firebase to deliver it.
}

/// [NotificationService] backed by Firebase Cloud Messaging.
///
/// Every method degrades to a safe no-op when Firebase is not configured, so
/// the app runs without push set up.
class FirebaseMessagingService implements NotificationService {
  FirebaseMessagingService();

  final _log = AppLogger.of('FCM');
  final _openedController = StreamController<NotificationMessage>.broadcast();
  final _subscriptions = <StreamSubscription<dynamic>>[];

  bool get _enabled => FirebaseInitializer.isReady;

  FirebaseMessaging get _messaging => FirebaseMessaging.instance;

  @override
  Future<void> initialize() async {
    if (!_enabled) {
      _log.info('Skipped: Firebase not configured.');
      return;
    }
    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
    _subscriptions
      ..add(FirebaseMessaging.onMessageOpenedApp.listen(_emitOpened))
      ..add(
        FirebaseMessaging.onMessage.listen(
          (m) => _log.fine('fg: ${m.messageId}'),
        ),
      );

    final initial = await _messaging.getInitialMessage();
    if (initial != null) _emitOpened(initial);
  }

  @override
  Future<NotificationPermissionStatus> requestPermission() async {
    if (!_enabled) return NotificationPermissionStatus.notDetermined;
    final settings = await _messaging.requestPermission();
    return _map(settings.authorizationStatus);
  }

  @override
  Future<NotificationPermissionStatus> currentStatus() async {
    if (!_enabled) return NotificationPermissionStatus.notDetermined;
    final settings = await _messaging.getNotificationSettings();
    return _map(settings.authorizationStatus);
  }

  @override
  Future<String?> getToken() async {
    if (!_enabled) return null;
    // Throws on iOS while the APNS token is not yet available; callers treat
    // "no token" and "not ready" the same, so degrade to null.
    try {
      return await _messaging.getToken();
    } catch (error) {
      _log.fine('getToken failed: $error');
      return null;
    }
  }

  @override
  Future<void> deleteToken() async {
    if (!_enabled) return;
    try {
      await _messaging.deleteToken();
    } catch (error) {
      _log.fine('deleteToken failed: $error');
    }
  }

  @override
  Stream<String> get onTokenRefreshed =>
      _enabled ? _messaging.onTokenRefresh : const Stream.empty();

  @override
  Stream<NotificationMessage> get onMessageOpened => _openedController.stream;

  void _emitOpened(RemoteMessage message) {
    _openedController.add(
      NotificationMessage(
        title: message.notification?.title,
        body: message.notification?.body,
        data: message.data,
      ),
    );
  }

  NotificationPermissionStatus _map(AuthorizationStatus status) =>
      switch (status) {
        AuthorizationStatus.authorized => NotificationPermissionStatus.granted,
        AuthorizationStatus.provisional =>
          NotificationPermissionStatus.provisional,
        AuthorizationStatus.denied => NotificationPermissionStatus.denied,
        AuthorizationStatus.notDetermined =>
          NotificationPermissionStatus.notDetermined,
      };

  /// Releases stream resources. Call when the owning provider is disposed.
  void dispose() {
    for (final sub in _subscriptions) {
      unawaited(sub.cancel());
    }
    _subscriptions.clear();
    unawaited(_openedController.close());
  }
}
